### ISSUE TITLE
Avoid dealing with Cells and Rows via Workbook

### ISSUE THREAD

**Issue by sabir-aspose** [fileformat-cells/FileFormat.Cells-for-.NET#5]
@fahadadeel 

<img width="602" alt="Screenshot at Oct 12 14-01-33" src="https://github.com/fileformat-cells/FileFormat.Cells-for-.NET/assets/781194/21a46541-19ad-4888-ab47-7796cf57dbfa">

As per XML Schema and looking at Workbook structure, cells and their contents belong to Worksheet. Therefore, any interactions with cells and contents belong to Worksheet instead of Workbook. Ideally, the objects flow should be like Workbook -> Worksheet -> Cell and then any operations should be performed via Cell object something like this:

`
Workbook wb = new Workbook();
Worksheet sheet = wb.Worksheets[0];
Cell cellA1 = sheet.Cells["A1"];
`

Then do something with contents of the cell. Therefore, I propose to remove all methods dealing with Cells from Workbook like below:

- DeleteTextFromCell(String, String, UInt32)
- GetCellValue(String, String)
- so on

**Comment by fahadadeel** [comment]
@sabir-aspose 

 I'm pleased to inform you that the issue has been addressed and resolved in my latest PR. Once the PR is merged, the fix will be available in the main branch.

Please find a demonstration of the corrected behavior:

using (Workbook wb = new Workbook(filePath))
{
    Worksheet firstSheet = wb.Worksheets[1];
    Cell cell = firstSheet.Cells["D2"];
    cell.PutValue("Fahad");
    wb.Save();
}

I encourage you to pull the changes from the main branch once merged and verify on your end. Let me know if you encounter any further concerns! Thanks
